import { ArrowUpRight, Download, MapPin, ArrowDown, Code2, Layers3, Terminal } from "lucide-react";
const skills = [
{title:"Languages & backend",icon:Code2,items:["Java","Spring Boot","Python","TypeScript","JavaScript","SQL","REST","gRPC"]},
{title:"Data & intelligence",icon:Layers3,items:["PostgreSQL","MSSQL","Redis","Vector search","HNSW","LLM APIs","RAG"]},
{title:"Interface & infrastructure",icon:Terminal,items:["React","Next.js","Tailwind CSS","Docker","Kubernetes","GitHub Actions","Traefik","Linux"]}
];
const experience = [
{company:"Rebul Group of Companies",role:"Software Developer",date:"Dec 2023 — Present",description:"Building and maintaining production backend services with Java and Spring Boot, with ownership through deployment and operational reliability.",points:["Containerized services with Docker, Kubernetes, and independent delivery pipelines.","PostgreSQL and MSSQL performance tuning through indexing, materialized views, batching, and query optimization.","Webhook-based marketplace integrations for order and logistics workflows."]},
{company:"Argela",role:"Software Developer Intern",date:"Jul 2023 — Aug 2023",description:"Built Python tooling to analyze and monitor a Kubernetes microservice system, using Redis caching and pagination to reduce repeated database queries.",points:["Prototyped a 5G channel-data streaming pipeline in Go using goroutines and channels."]},
{company:"Teknomina Informatics",role:"Web Developer Intern",date:"Aug 2022 — Sep 2022",description:"Developed RESTful services with Java, Spring Boot, MVC, and JDBC. Rebuilt the company website in React with responsive layouts and dynamic API-powered content.",points:[]}
];
export default function Home(){return <>
<a className="skip" href="#main">Skip to content</a>
<header className="header wrap"><a className="wordmark" href="#" aria-label="Eyüp Akdeniz home">ea<span>.</span></a><nav aria-label="Main navigation"><a href="#about">About</a><a href="#experience">Experience</a><a href="#skills">Skills</a></nav><a className="header-contact" href="mailto:eyupakdeniz99@gmail.com">Let’s talk <ArrowUpRight size={17}/></a></header>
<main id="main" className="wrap">
<section className="hero" id="about"><div className="hero-copy"><p className="eyebrow">SOFTWARE DEVELOPER <span>/</span> ISTANBUL, TÜRKİYE</p><h1>Eyüp<br/>Akdeniz<span className="accent">.</span></h1><p className="hero-statement">From the first data model<br/>to the last mile of deployment.</p><p className="intro">I build software and take ownership of what comes after. Backend services, the interfaces people use, and the infrastructure that keeps it all running.</p><div className="hero-actions"><a className="button" href="/eyup-akdeniz-resume.pdf" download>Download résumé <Download size={17}/></a><a className="text-link" href="https://github.com/eyupakdniz" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={17}/></a></div></div>
<aside className="profile-note" aria-label="Professional focus"><div className="note-top"><span>THE WAY I BUILD</span><Code2 size={21}/></div><p className="note-heading">Own the<br/><em>whole</em> problem.</p><div className="flow"><span>01 <b>Model the data</b></span><span>02 <b>Build the service</b></span><span>03 <b>Ship & keep it running</b></span></div><div className="note-bottom"><MapPin size={15}/> Istanbul, Türkiye</div></aside>
<div className="hero-bottom"><span>Java & Spring Boot · Distributed systems · DevOps</span><a href="#experience">Explore my background <ArrowDown size={16}/></a></div></section>
<section className="section" id="experience"><div className="section-heading"><p className="eyebrow">01 / EXPERIENCE</p><h2>Built in practice.</h2><p>From early internships to owning production services.</p></div><div className="timeline">{experience.map((job,i)=><article className="job" key={job.company}><div className="job-meta"><span>{job.date}</span>{i===0&&<span className="current">Current role</span>}</div><div><h3>{job.company}</h3><p className="role">{job.role}</p><p>{job.description}</p>{job.points.length>0&&<ul>{job.points.map(point=><li key={point}>{point}</li>)}</ul>}</div></article>)}</div></section>
<section className="section" id="skills"><div className="section-heading"><p className="eyebrow">02 / TOOLKIT</p><h2>The tools behind the work.</h2></div><div className="skills-grid">{skills.map(({title,icon:Icon,items})=><article className="skill-group" key={title}><Icon size={23}/><h3>{title}</h3><div className="tags">{items.map(item=><span key={item}>{item}</span>)}</div></article>)}</div></section>
<section className="section direction"><div><p className="eyebrow">03 / WHAT’S NEXT</p><h2>Thinking in systems.<br/><span>Building for scale.</span></h2><p>I want to build distributed backends that stay correct under load and across service boundaries, and the delivery infrastructure that lets a team ship safely and often.</p></div><aside className="education"><p className="eyebrow">EDUCATION</p><h3>Fırat University</h3><p>B.Sc. Computer Engineering</p><span>2019 — 2023 · Elazığ, Türkiye</span></aside></section>
<section className="contact"><p className="eyebrow">GET IN TOUCH</p><h2>Let’s build something<br/>that works.</h2><a className="email" href="mailto:eyupakdeniz99@gmail.com">eyupakdeniz99@gmail.com <ArrowUpRight/></a><div className="socials"><a href="https://github.com/eyupakdniz" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={15}/></a><a href="https://linkedin.com/in/eyupakdeniz/" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={15}/></a><a href="https://dev.to/eyupakdniz" target="_blank" rel="noreferrer">dev.to <ArrowUpRight size={15}/></a></div></section>
</main><footer className="wrap footer"><a className="wordmark" href="#" aria-label="Back to top">ea<span>.</span></a><p>Eyüp Akdeniz · Software Developer</p><a href="#">Back to top ↑</a></footer></>}

