import { ArrowUpRight, Download, MapPin, Code2, Layers3, Terminal, FileText, Briefcase, GraduationCap, Mail, ChevronRight, Lightbulb } from "lucide-react";
const skills = [
{title:"Languages & backend",icon:Code2,items:["Java","Spring Boot","Python","TypeScript","JavaScript","SQL","REST","gRPC"]},
{title:"Data & intelligence",icon:Layers3,items:["PostgreSQL","MSSQL","Redis","Vector search","HNSW","LLM APIs","RAG"]},
{title:"Interface & infrastructure",icon:Terminal,items:["React","Next.js","Tailwind CSS","Docker","Kubernetes","GitHub Actions","Traefik","Linux"]}
];
const experience = [
{company:"Rebul Group of Companies",role:"Software Developer",date:"Dec 2023 — Present",description:"Building and maintaining production backend services with Java and Spring Boot, with ownership through deployment and operational reliability.",points:["Containerized services with Docker, Kubernetes, and independent delivery pipelines.","PostgreSQL and MSSQL performance tuning through indexing, materialized views, batching, and query optimization.","Webhook-based marketplace integrations for order and logistics workflows."]},
{company:"Argela",role:"Software Developer Intern",date:"Jul 2023 — Aug 2023",description:"Built Python tooling to analyze and monitor a Kubernetes microservice system, using Redis caching and pagination to reduce repeated database queries.",points:["Prototyped a 5G channel-data streaming pipeline in Go using goroutines and channels."]},
{company:"Teknomina Informatics",role:"Web Developer Intern",date:"Aug 2022 — Sep 2022",description:"Developed RESTful services with Java, Spring Boot, MVC, and JDBC. Rebuilt the company website in React with responsive layouts and dynamic API-powered content.",points:[]}
];
const sections=[{id:"about",label:"About me",icon:FileText},{id:"experience",label:"Experience",icon:Briefcase},{id:"skills",label:"Technical skills",icon:Code2},{id:"education",label:"Education",icon:GraduationCap},{id:"contact",label:"Get in touch",icon:Mail}];
export default function Home(){return <>
<a className="skip" href="#main">Skip to content</a>
<aside className="sidebar"><a className="workspace" href="#about"><span className="avatar">E</span> Eyüp’s space</a><p className="sidebar-label">Personal</p><a className="page-link" href="#about"><ChevronRight size={15}/><span aria-hidden="true">👋</span> About me</a><nav aria-label="Page sections">{sections.slice(1).map(({id,label,icon:Icon})=><a href={`#${id}`} key={id}><Icon size={16}/>{label}</a>)}</nav><div className="sidebar-bottom"><a href="/eyup-akdeniz-resume.pdf" download><Download size={16}/> Download résumé</a><span>Made of curiosity & code.</span></div></aside>
<div className="page-shell"><header className="topbar"><a href="#about"><span aria-hidden="true">👋</span> Eyüp Akdeniz <span className="slash">/</span> <span>About me</span></a><a className="top-resume" href="/eyup-akdeniz-resume.pdf" download><Download size={15}/> Résumé</a></header>
<main id="main" className="document"><section id="about" className="about"><div className="page-icon" aria-hidden="true">👋</div><h1>Eyüp Akdeniz</h1><p className="subtitle">Software developer. From data models to deployment.</p><dl className="properties"><div><dt><Briefcase size={16}/> Role</dt><dd>Software Developer <span className="tag blue">Rebul Group</span></dd></div><div><dt><MapPin size={16}/> Based in</dt><dd>Istanbul, Türkiye</dd></div><div><dt><Code2 size={16}/> Focus</dt><dd className="property-tags"><span className="tag purple">Backend engineering</span><span className="tag green">Distributed systems</span><span className="tag gray">DevOps</span></dd></div><div><dt><Mail size={16}/> Email</dt><dd><a href="mailto:eyupakdeniz99@gmail.com">eyupakdeniz99@gmail.com</a></dd></div></dl>
<div className="intro"><p>Hi, I’m Eyüp — a software developer who likes owning a problem end to end.</p><p>I work across the data model, the interface people actually use, and the infrastructure that keeps it running. I care about what happens after the pull request, too.</p></div><aside className="callout"><Lightbulb size={22}/><div><strong>Own the whole problem.</strong><p>Model the data. Build the service. Ship it and keep it running.</p></div></aside><div className="links"><a href="/eyup-akdeniz-resume.pdf" download><FileText size={17}/> Download résumé</a><a href="https://github.com/eyupakdniz" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={14}/></a><a href="https://linkedin.com/in/eyupakdeniz/" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={14}/></a><a href="https://dev.to/eyupakdniz" target="_blank" rel="noreferrer">dev.to <ArrowUpRight size={14}/></a></div></section>
<section id="experience" className="section"><h2><span aria-hidden="true">💼</span> Experience</h2>{experience.map((job,i)=><details className="job" key={job.company} open><summary><ChevronRight className="toggle" size={17}/><span className="job-title">{job.company}</span>{i===0&&<span className="tag green">Current</span>}</summary><div className="job-body"><div className="job-meta"><strong>{job.role}</strong><span>{job.date}</span></div><p>{job.description}</p>{job.points.length>0&&<ul>{job.points.map(point=><li key={point}>{point}</li>)}</ul>}</div></details>)}</section>
<section id="skills" className="section"><h2><span aria-hidden="true">🧰</span> Technical skills</h2><div className="skill-table">{skills.map(({title,icon:Icon,items},i)=><div className="skill-row" key={title}><h3><Icon size={17}/>{title}</h3><div className="tags">{items.map(item=><span className={`tag ${["gray","purple","blue"][i]}`} key={item}>{item}</span>)}</div></div>)}</div></section>
<section id="education" className="section"><h2><span aria-hidden="true">🎓</span> Education</h2><div className="education"><h3>Fırat University</h3><p>B.Sc. Computer Engineering</p><span>2019 — 2023</span></div></section>
<section className="section"><h2><span aria-hidden="true">🌱</span> What I want to build next</h2><p>Distributed backends that stay correct under load and across service boundaries, and the delivery infrastructure that lets a team ship safely and often.</p></section>
<section id="contact" className="section contact"><h2><span aria-hidden="true">✉️</span> Get in touch</h2><p>Have something in mind? Let’s talk.</p><a href="mailto:eyupakdeniz99@gmail.com">eyupakdeniz99@gmail.com <ArrowUpRight size={16}/></a></section><footer><span>Eyüp Akdeniz · Software Developer</span><a href="#about">Back to top ↑</a></footer></main></div></>}

